// src/components/Button.vue
<script setup lang="ts">
import styles from "./Button.module.css";

withDefaults(
  defineProps<{
    href?: string;
    variant?: "default" | "primary";
    block?: boolean;
    title?: string;
    id?: string;
    disabled?: boolean;
  }>(),
  { variant: "default", block: false },
);

defineEmits<{ click: [event: MouseEvent] }>();
</script>

<template>
  <a
    v-if="href !== undefined"
    :href="href"
    :class="[styles.button, variant === 'primary' && styles.primary, block && styles.block]"
    :title="title"
    :id="id"
  >
    <slot />
  </a>
  <button
    v-else
    type="button"
    :class="[styles.button, variant === 'primary' && styles.primary, block && styles.block]"
    :title="title"
    :id="id"
    :disabled="disabled"
    @click="$emit('click', $event)"
  >
    <slot />
  </button>
</template>

// components/Button.tsx
import type { ComponentChildren } from "preact";
import styles from "./Button.module.css";

interface ButtonProps {
  children: ComponentChildren;
  /** Renders a link styled as a button. */
  href?: string;
  variant?: "default" | "primary";
  block?: boolean;
  class?: string;
  title?: string;
  id?: string;
  disabled?: boolean;
  onClick?: (event: MouseEvent) => void;
}

export function Button(props: ButtonProps) {
  const { children, href, variant = "default", block, class: extra, ...rest } = props;
  const className = [
    styles.button,
    variant === "primary" && styles.primary,
    block && styles.block,
    extra,
  ].filter(Boolean).join(" ");

  if (href !== undefined) {
    return (
      <a href={href} class={className} title={rest.title} id={rest.id}>
        {children}
      </a>
    );
  }
  return (
    <button type="button" class={className} {...rest}>
      {children}
    </button>
  );
}
