// src/components/DropdownMenu.vue
<script setup lang="ts">
import { onMounted, onUnmounted, ref, watch } from "vue";
import styles from "./DropdownMenu.module.css";

const props = withDefaults(defineProps<{
  id?: string;
  open: boolean;
  placement?: "bottom-start" | "bottom-end";
}>(), { placement: "bottom-start" });
const emit = defineEmits<{ "open-change": [open: boolean] }>();
const root = ref<HTMLDivElement | null>(null);

function onDocumentClick(event: MouseEvent): void {
  if (!root.value?.contains(event.target as Node | null)) emit("open-change", false);
}

function onMenuClick(event: MouseEvent): void {
  const item = (event.target as HTMLElement).closest('[role^="menuitem"]');
  if (
    item && !item.hasAttribute("data-keep-open") && item.getAttribute("aria-haspopup") !== "true"
  ) emit("open-change", false);
}

watch(() => props.open, (open) => {
  if (open) document.addEventListener("click", onDocumentClick);
  else document.removeEventListener("click", onDocumentClick);
});
onMounted(() => {
  if (props.open) document.addEventListener("click", onDocumentClick);
});
onUnmounted(() => document.removeEventListener("click", onDocumentClick));
</script>

<template>
  <div :class="styles.root" :id="id" ref="root" :data-open="String(open)">
    <div :class="styles.trigger" @click="emit('open-change', !open)">
      <slot name="trigger" />
    </div>
    <div
      :class="[styles.popover, styles[placement], open && styles.open]"
      role="menu"
      @click="onMenuClick"
    >
      <slot />
    </div>
  </div>
</template>

// components/DropdownMenu.tsx
import type { ComponentChildren } from "preact";
import { useEffect, useRef } from "preact/hooks";
import styles from "./DropdownMenu.module.css";

interface DropdownMenuProps {
  id?: string;
  open: boolean;
  onOpenChange: (open: boolean) => void;
  placement?: "bottom-start" | "bottom-end";
  trigger: ComponentChildren;
  children: ComponentChildren;
}

/** A menu popover. Items close it on click unless they carry `data-keep-open`. */
export function DropdownMenu(
  { id, open, onOpenChange, placement = "bottom-start", trigger, children }: DropdownMenuProps,
) {
  const root = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (!open) return;
    const onDocumentClick = (event: MouseEvent) => {
      if (!root.current?.contains(event.target as Node | null)) onOpenChange(false);
    };
    document.addEventListener("click", onDocumentClick);
    return () => document.removeEventListener("click", onDocumentClick);
  }, [open, onOpenChange]);

  function onMenuClick(event: MouseEvent): void {
    const item = (event.target as HTMLElement).closest('[role^="menuitem"]');
    if (
      item && !item.hasAttribute("data-keep-open") && item.getAttribute("aria-haspopup") !== "true"
    ) {
      onOpenChange(false);
    }
  }

  return (
    <div class={styles.root} id={id} ref={root} data-open={String(open)}>
      <div class={styles.trigger} onClick={() => onOpenChange(!open)}>{trigger}</div>
      <div
        class={`${styles.popover} ${styles[placement]} ${open ? styles.open : ""}`}
        role="menu"
        onClick={onMenuClick}
      >
        {children}
      </div>
    </div>
  );
}
